[C++23] Add missing headers
Add algorithm, atomic, cstdint, memory, and deque headers to
resolve undeclared identifier errors caused by C++23. C++23
removed transitive includes so you have to add the necessary C++
headers.

Errors:
frameworks/native/include/binder/BinderNetlink.h:70:10: error: no
template named 'unique_ptr' in namespace 'std'
   70 |     std::unique_ptr<nl_sock, void (*)(nl_sock*)> mMcSock;
frameworks/native/services/surfaceflinger/common/include/common/Panopticon.h:77:10:
error: no type named 'atomic_int64_t' in namespace 'std'
   77 |     std::atomic_int64_t startTime = -1;
frameworks/native/services/surfaceflinger/common/include/common/Panopticon.h:78:10:
error: no type named 'atomic_int64_t' in namespace 'std'
   78 |     std::atomic_int64_t endTime = -1;
frameworks/native/services/surfaceflinger/common/include/common/Panopticon.h:79:10:
error: no type named 'atomic_bool' in namespace 'std'
   79 |     std::atomic_bool isTracing = false;
frameworks/native/services/surfaceflinger/common/include/common/Panopticon.h:80:10:
error: no type named 'atomic_int32_t' in namespace 'std'
   80 |     std::atomic_int32_t cookie = -1;
frameworks/native/services/surfaceflinger/common/include/common/Panopticon.h:148:10:
error: no type named 'atomic_int32_t' in namespace 'std'
  148 |     std::atomic_int32_t mTracingCookie;
frameworks/native/services/surfaceflinger/common/include/common/Panopticon.h:133:68:
error: no matching member function for call to 'shared_from_this'
  133 |     SliceToken makeSlice(SliceType type) { return
SliceToken(type, shared_from_this()); }
frameworks/native/services/vibrationflinger/include/vibrationflinger/HapticGeneratorStream.h:89:75:
error: implicit instantiation of undefined template
'std::deque<aidl::android::hardware::vibrator::VibrationEffectContent>'
   89 |
std::deque<aidl::android::hardware::vibrator::VibrationEffectContent>
mPendingEffects

Generated by Gemini.

Flag: EXEMPT PURE_REFACTOR
Bug: 429048222
Test: m libbindernetlink libcompositionengine libvibrationflinger libprotolog binderAllocationLimits
Change-Id: Ia51a7b8ac3fd9625a134b0190f7505ba2b9033f0