[C++23] Fix Wthread-safety-analysis due to FakeGuard with C++23
In C++23 and above, the FakeGuard class is kept alive until the end of
function so it never has the release_capability attribute attached to
the mutex causing thread-safety-analysis warning to say the mutex is
still held till the end of the function. To fix this, we move the
FTL_FAKE_GUARD out of the loop guard and pass the reference variable.

Error:
frameworks/native/services/surfaceflinger/tests/unittests/TestableSurfaceFlinger.h:344:5:
error: mutex 'mFlinger->mStateLock' is still held at the end of function
[-Werror,-Wthread-safety-analysis]
  344 |     }
frameworks/native/services/surfaceflinger/tests/unittests/TestableSurfaceFlinger.h:334:14:
note: mutex acquired here
  334 |              FTL_FAKE_GUARD(mFlinger->mStateLock,
mFlinger->mPhysicalDisplays)) {

frameworks/native/services/surfaceflinger/SurfaceFlinger.cpp:3513:1:
error: mutex 'mStateLock' is still held at the end of function
[-Werror,-Wthread-safety-analysis]
 3513 | }
      | ^
frameworks/native/services/surfaceflinger/SurfaceFlinger.cpp:3449:37:
note: mutex acquired here
 3449 |     for (const auto& [_, display] : FTL_FAKE_GUARD(mStateLock,
mDisplays)) {

Flag: EXEMPT BUGFIX
Bug: 429048222
Bug: 474082422
Test: m libsurfaceflinger_unittest surfaceflinger
Test: m surfaceflinger_microbenchmarks
Change-Id: Icd23359c399a87f85a29fe458b4c057b9d11a2a0